{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[30s])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(traefik_entrypoint_request_duration_seconds_bucket{code=\"200\",le=\"0.1\"}[30s]) \n/ ignoring (le) increase(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[30s])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code!=\"200\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average entrypoint response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_sum{code=\"200\"}[30s])) by (job)\n/\nsum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\"}[30s])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Average backend response time [30s]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_request_duration_seconds_sum{code=\"200\",backend!~\".*local.*\"}[30s])\n/\nrate(traefik_backend_request_duration_seconds_count{code=\"200\",backend!~\".*local.*\"}[30s])",
     "legendFormat": "{{ job }} / {{ backend }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Traefik config reloads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "traefik_config_reloads_total", "legendFormat": "{{ job }}" }
   ]
  }
 ]
}